export const pageEndPoints = {
    dashboard: '/',
    login: '/login',
}

export const apiEndPoints = {
    login: '/login',
}

export const symbolOpt = [
    { value: "Please Choose Stocks", name: "Please Choose Stocks" },
    { value: "SBID89", name: "SBID89 (9% Nepal SBI Bank Rinpatra 2089)" },
    { value: "GBILD84/85", name: "GBILD84/85 (Global IME Bank Debenture 2084/85)" },
    { value: "NIFRAUR85/86", name: "NIFRAUR85/86 (NIFRA Uraj Rinpatra7%-2085/86)" },
    { value: "PSF", name: "PSF (Prabhu Select Fund)" },
    { value: "NICGF2", name: "NICGF2 (Nic Asia Growth Fund 2)" },
    { value: "KSY", name: "KSY (Kumari Sabal Yojana)" },
    { value: "H8020", name: "H8020 (Himalayan 80-20)" },
    { value: "NIMBD90", name: "NIMBD90 (10% NIMB Debenture 2090)" },
    { value: "NIBLSTF", name: "NIBLSTF (NIBL STABLE FUND)" },
    { value: "NMBD2085", name: "NMBD2085 (10 % NMB DEBENTURE 2085)" },
    { value: "LBBLD89", name: "LBBLD89 (11% LBBL Debenture 2089)" },
    { value: "ILI", name: "ILI (IME Life Insurance Company Limited)" },
    { value: "UPCL", name: "UPCL (UNIVERSAL POWER COMPANY LTD)" },
    { value: "SBLD83", name: "SBLD83 (10.25% SBL Debenture 2083)" },
    { value: "IGI", name: "IGI (IGI Prudential Insurance Limited)" },
    { value: "SJLIC", name: "SJLIC (Suryajyoti Life Insurance Company Limited)" },
    { value: "GBBD85", name: "GBBD85 (8.75% Garima Debenture 2085)" },
    { value: "HDL", name: "HDL (Himalayan Distillery Limited)" },
    { value: "SHINE", name: "SHINE (Shine Resunga Development Bank Ltd.)" },
    { value: "NGPL", name: "NGPL (Ngadi Group Power Ltd.)" },
    { value: "MNBBL", name: "MNBBL (Muktinath Bikas Bank Ltd.)" },
    { value: "NLG", name: "NLG (NLG Insurance Company Ltd.)" },
    { value: "AHL", name: "AHL (Asian Hydropower Limited)" },
    { value: "GLBSL", name: "GLBSL (Gurans Laghubitta Bittiya Sanstha Limited)" },
    { value: "HDHPC", name: "HDHPC (Himal Dolakha Hydropower Company Limited)" },
    { value: "SFCL", name: "SFCL (Samriddhi Finance Company Limited)" },
    { value: "DORDI", name: "DORDI (Dordi Khola Jalbidhyut Company Limited)" },
    { value: "SMHL", name: "SMHL (Super Madi Hydropower Limited)" },
    { value: "CIZBD86", name: "CIZBD86 (10.25% Citizens Bank Debenture 2086)" },
    { value: "SHPC", name: "SHPC (Sanima Mai Hydropower Ltd.)" },
    { value: "GBBL", name: "GBBL (Garima Bikas Bank Limited)" },
    { value: "ALBSL", name: "ALBSL (Asha Laghubitta Bittiya Sanstha Ltd)" },
    { value: "ADBLD83", name: "ADBLD83 (10.35% ADBL Krisi Bank Rinpatra 2083)" },
    { value: "PFL", name: "PFL (Pokhara Finance Ltd.)" },
    { value: "NBLD82", name: "NBLD82 (10% Nabil Debenture 2082)" },
    { value: "UNL", name: "UNL (Unilever Nepal Limited)" },
    { value: "MMKJL", name: "MMKJL (Mathillo Mailun Khola Jalvidhyut Limited)" },
    { value: "SDBD87", name: "SDBD87 (10 years, 9%, Shangrila Development Bank Debenture 2087)" },
    { value: "EBL", name: "EBL (Everest Bank Limited)" },
    { value: "SFMF", name: "SFMF (Sunrise First Mutual Fund)" },
    { value: "RBCL", name: "RBCL (Rastriya Beema Company Limited)" },
    { value: "PPL", name: "PPL (People`s Power Limited)" },
    { value: "SMH", name: "SMH (Supermai Hydropower Limited)" },
    { value: "MERO", name: "MERO (Mero Microfinance Bittiya Sanstha Ltd.)" },
    { value: "BNHC", name: "BNHC (Buddha Bhumi Nepal Hydro Power Co. Ltd.)" },
    { value: "BOKD86", name: "BOKD86 (8.5% BOK Debenture 2086)" },
    { value: "NICA", name: "NICA (NIC Asia Bank Ltd.)" },
    { value: "NIBD84", name: "NIBD84 (8.5% Nepal Investment Bank Bond 2084)" },
    { value: "SNLI", name: "SNLI (Sun Nepal Life Insurance Company Limited)" },
    { value: "HBLD83", name: "HBLD83 (10% Himalayan Bank Ltd. Debenture 2083)" },
    { value: "BHPL", name: "BHPL (Barahi Hydropower Public Limited)" },
    { value: "NBBD2085", name: "NBBD2085 (10.25% NBBL Debenture 2085)" },
    { value: "ULBSL", name: "ULBSL (Upakar Laghubitta Bittiya Sanstha Limited)" },
    { value: "VLBS", name: "VLBS (Vijaya laghubitta Bittiya Sanstha Ltd.)" },
    { value: "RMF1", name: "RMF1 (RBB Mutual Fund 1)" },
    { value: "PRSF", name: "PRSF (Prabhu Smart Fund)" },
    { value: "NICGF", name: "NICGF (NIC Asia Growth Fund)" },
    { value: "NMB50", name: "NMB50 (NMB 50)" },
    { value: "CMF1", name: "CMF1 (Citizens Mutual Fund -1)" },
    { value: "SBD87", name: "SBD87 (8.5% Sanima Debenture 2087)" },
    { value: "HATHY", name: "HATHY (Hathway Investment Nepal Limited)" },
    { value: "NIBLGF", name: "NIBLGF (NIBL Growth Fund)" },
    { value: "API", name: "API (API Power Company Limited)" },
    { value: "PMHPL", name: "PMHPL (Panchakanya Mai Hydropower Ltd)" },
    { value: "KMCDB", name: "KMCDB (Kalika Microcredit Development Bank Ltd.)" },
    { value: "EBLD86", name: "EBLD86 (Everest Bank Limited Debenture 2086)" },
    { value: "NICAD8182", name: "NICAD8182 (NIC Asia Debenture 2081/82)" },
    { value: "SAND2085", name: "SAND2085 (Sanima Bank Limited Debenture)" },
    { value: "ANLB", name: "ANLB (Aatmanirbhar Laghubitta Bittiya Sanstha Limited)" },
    { value: "LLBS", name: "LLBS (Laxmi Laghubitta Bittiya Sanstha Ltd.)" },
    { value: "CGH", name: "CGH (Chandragiri Hills Limited)" },
    { value: "AHPC", name: "AHPC (Arun Valley Hydropower Development Co. Ltd.)" },
    { value: "BNT", name: "BNT (Bottlers Nepal (Terai) Limited)" },
    { value: "HLI", name: "HLI (Himalayan Life Insurance Limited)" },
    { value: "UAIL", name: "UAIL (United Ajod Insurance Limited)" },
    { value: "LICN", name: "LICN (Life Insurance Co. Nepal)" },
    { value: "MMF1", name: "MMF1 (Mega Mutual Fund 1)" },
    { value: "SPIL", name: "SPIL (Siddhartha Premier Insurance Limited)" },
    { value: "KBLD86", name: "KBLD86 (10.25% Kumari Bank Debenture 2086)" },
    { value: "NABBC", name: "NABBC (Narayani Development Bank Limited)" },
    { value: "SIFC", name: "SIFC (Shree Investment Finance Co. Ltd.)" },
    { value: "NRM", name: "NRM (Nepal Republic Media Limited)" },
    { value: "DOLTI", name: "DOLTI (Dolti Power Company Ltd)" },
    { value: "SALICO", name: "SALICO (Sagarmatha Lumbini Insurance Company Limited)" },
    { value: "MANDU", name: "MANDU (Mandu Hydropower Limited)" },
    { value: "CMF2", name: "CMF2 (CITIZENS MUTUAL FUND 2)" },
    { value: "NLICL", name: "NLICL (National Life Insurance Co. Ltd.)" },
    { value: "ADBL", name: "ADBL (Agricultural Development Bank Limited)" },
    { value: "KDBY", name: "KDBY (Kumari Dhanabriddhi Yojana)" },
    { value: "PRIN", name: "PRIN (Prabhu Insurance Ltd.)" },
    { value: "PBLD86", name: "PBLD86 (10.25% Prabhu Bank Debenture 2086)" },
    { value: "MHCL", name: "MHCL (Molung Hydropower Company Limited)" },
    { value: "SRBLD83", name: "SRBLD83 (10.25% Sunrise Bank Debenture 2083)" },
    { value: "CFCL", name: "CFCL (Central Finance Co. Ltd.)"},
    { value: "RURU", name: "RURU (Ru Ru Jalbidhyut Pariyojana Limited)" },
    { value: "RLFL", name: "RLFL (Reliance Finance Ltd.)" },
    { value: "SCBD", name: "SCBD (10.30% Standard Chartered Bank Nepal Limited Debenture)" },
    { value: "SONA", name: "SONA (Sonapur Minerals and Oil Limited)" },
    { value: "RAWA", name: "RAWA (Rawa Energy Development Limited)" },
    { value: "BBC", name: "BBC (Bishal Bazar Company Limited)" },
    { value: "MCHL", name: "MCHL (Menchhiyam Hydropower Limited)" },
    { value: "AKJCL", name: "AKJCL (Ankhu Khola Jalvidhyut Company Ltd)" },
    { value: "MDB", name: "MDB (Miteri Development Bank Limited)" },
    { value: "MKJC", name: "MKJC (Mailung Khola Jal Vidhyut Company Limited)" },
    { value: "ULHC", name: "ULHC (Upper Lohore Hydropower Company Limited)" },
    { value: "GIBF1", name: "GIBF1 (Global IME Balanced Fund - 1)" },
    { value: "GMFBS", name: "GMFBS (Ganapati Microfinance Bittiya Sanstha Limited)" },
    { value: "SPC", name: "SPC (Samling Power Company Limited)" },
    { value: "CLI", name: "CLI (Citizen Life Insurance Company Limited)" },
    { value: "CHCL", name: "CHCL (Chilime Hydropower Company Limited)" },
    { value: "MBLD2085", name: "MBLD2085 (10.25% Machhapuchchhre Debenture 2085)" },
    { value: "ILBS", name: "ILBS (Infinity Laghubitta Bittiya Sanstha Limited)" },
    { value: "JSLBB", name: "JSLBB (Janautthan Samudayic Laghubitta Bikas Bank Ltd.)" },
    { value: "KDL", name: "KDL (Kalinchowk Darshan Limited)" },
    { value: "SAPDBL", name: "SAPDBL (Saptakoshi Development Bank Ltd)" },
    { value: "USLB", name: "USLB (Unnati Sahakarya Laghubitta Bittiya Sanstha Limited)" },
    { value: "NICLBSL", name: "NICLBSL (NIC ASIA Laghubitta Bittiya Sanstha Limited)" },
    { value: "BARUN", name: "BARUN (Barun Hydropower Co. Ltd.)" },
    { value: "PCBL", name: "PCBL (Prime Commercial Bank Ltd.)" },
    { value: "SICL", name: "SICL (Shikhar Insurance Co. Ltd.)" },
    { value: "SIGS3", name: "SIGS3 (Siddhartha Investment Growth Scheme 3)" },
    { value: "GCIL", name: "GCIL (Ghorahi Cement Industry Limited)" },
    { value: "MSHL", name: "MSHL (Mid Solu Hydropower Company Limited)" },
    { value: "TSHL", name: "TSHL (Three Star Hydropower Limited)" },
    { value: "NMFBS", name: "NMFBS (National Microfinance Bittiya Sanstha Ltd.)" },
    { value: "NICAD8283", name: "NICAD8283 (11% NIC Asia Debenture 082/83)" },
    { value: "PPCL", name: "PPCL (Panchthar Power Compant Limited)" },
    { value: "UMHL", name: "UMHL (United Modi Hydropower Ltd.)" },
    { value: "PROFL", name: "PROFL (ProgressiveFinance Limited)" },
    { value: "BNL", name: "BNL (Bottlers Nepal (Balaju) Limited)" },
    { value: "CIT", name: "CIT (Citizen Investment Trust)" },
    { value: "MKHC", name: "MKHC (Maya Khola Hydropower Company Limited)" },
    { value: "NABIL", name: "NABIL (Nabil Bank Limited)" },
    { value: "USHEC", name: "USHEC (Upper Solu Hydro Electric Company Limited)" },
    { value: "WNLB", name: "WNLB (Wean Nepal Laghubitta Bittiya Sanstha Ltd.)" },
    { value: "MLBL", name: "MLBL (Mahalaxmi Bikas Bank Ltd.)" },
    { value: "NLO", name: "NLO (Nepal Lube Oil Limited)" },
    { value: "NWCL", name: "NWCL (Nepal Warehousing Company Ltd)" },
    { value: "RADHI", name: "RADHI (Radhi Bidyut Company Ltd)" },
    { value: "TPC", name: "TPC (Terhathum Power Company Limited)" },
    { value: "NBLD87", name: "NBLD87 (8.5% Nepal Bank Debenture 2087)" },
    { value: "GILB", name: "GILB (Global IME Laghubitta Bittiya Sanstha Ltd.)" },
    { value: "TAMOR", name: "TAMOR (Sanima Middle Tamor Hydropower Limited)" },
    { value: "GVL", name: "GVL (Green Ventures Limited)" },
    { value: "MEL", name: "MEL (Modi Energy Limited)" },
    { value: "GUFL", name: "GUFL (Gurkhas Finance Ltd.)" },
    { value: "NCCD86", name: "NCCD86 (9.5% NCC Rinpatra 2086)" },
    { value: "HIDCL", name: "HIDCL (Hydroelectricity Investment and Development Company Ltd)" },
    { value: "KBLD89", name: "KBLD89 (11% KBL Debenture 2089)" },
    { value: "GLH", name: "GLH (GREENLIFE HYDROPOWER LIMITED)" },
    { value: "CYCL", name: "CYCL (Cyc Nepal Laghubitta Bittiya Sanstha Limited)" },
    { value: "SBLD89", name: "SBLD89 (10.75% SBL Debenture 2089)" },
    { value: "SBL", name: "SBL (Siddhartha Bank Limited)" },
    { value: "SBD89", name: "SBD89 (10.25% Sanima Debenture 2089)" },
    { value: "GRDBL", name: "GRDBL (Green Development Bank Ltd.)" },
    { value: "JBBL", name: "JBBL (Jyoti Bikas Bank Limited)" },
    { value: "NICFC", name: "NICFC (NIC Asia Flexi Cap Fund)" },
    { value: "KBSH", name: "KBSH (Kutheli Bukhari Small Hydropower Limited)" },
    { value: "CBBL", name: "CBBL (Chhimek Laghubitta Bittiya Sanstha Limited)" },
    { value: "PBD88", name: "PBD88 (10% Prime Debenture 2088)" },
    { value: "PBD85", name: "PBD85 (8 years, 8.75% Prime Debenture 2085)" },
    { value: "CHDC", name: "CHDC (CEDB Holdings Limited)" },
    { value: "RHGCL", name: "RHGCL (Rapti Hydro and General Construction Limited)" },
    { value: "SBID83", name: "SBID83 (10.25% Nepal SBI Bank Debenture 2083)" },
    { value: "MPFL", name: "MPFL (Multipurpose Finance Company Limited)" },
    { value: "SMFBS", name: "SMFBS (Swabhimaan Laghubitta Bittiya Sanstha Limited)" },
    { value: "NRIC", name: "NRIC (Nepal Reinsurance Company Limited)" },
    { value: "SHEL", name: "SHEL (Singati Hydro Energy Limited)" },
    { value: "GBLBS", name: "GBLBS (Grameen Bikas Laghubitta Bittiya Sanstha Ltd.)" },
    { value: "HHL", name: "HHL (Himalayan Hydropower Limited)" },
    { value: "SWMF", name: "SWMF (Suryodaya Womi Laghubitta Bittiya Sanstha Limited)" },
    { value: "NBF3", name: "NBF3 (Nabil Balance Fund III)" },
    { value: "NICBF", name: "NICBF (NIC Asia Balanced Fund)" },
    { value: "NICD83/84", name: "NICD83/84 (10.25% NIC Asia Debenture 2083/84)" },
    { value: "CORBL", name: "CORBL (Corporate Development Bank Limited)" },
    { value: "CIZBD90", name: "CIZBD90 (10% Citizens Bank Debenture 2090)" },
    { value: "VLUCL", name: "VLUCL (Vision Lumbini Urja Company Limited)" },
    { value: "TVCL", name: "TVCL (Trishuli Jal Vidhyut Company Limited)" },
    { value: "SMPDA", name: "SMPDA (Sampada Laghubitta Bittiya Sanstha Limited)" },
    { value: "NMLBBL", name: "NMLBBL (Nerude Mirmire Laghubitta Bittiya Sanstha Limited)" },
    { value: "BGWT", name: "BGWT (Bhagawati Hydropower Development Company Ltd)" },
    { value: "ADBLB86", name: "ADBLB86 (8 Years, 4% Agriculture Bond)" },
  ];
  